name: Wazuh Docker Compose CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy-and-test:
    name: Deploy Stack and Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          docker-compose \
          chromium-browser \
          xvfb
        
    - name: Generate Wazuh indexer certificates
      run: |
        cd wazuh-docker/single-node
        echo "Generating Wazuh indexer certificates..."
        docker-compose -f generate-indexer-certs.yml run --rm generator
        ls -la config/wazuh_indexer_ssl_certs/
        
    - name: Generate self-signed SSL certificate for Nginx
      run: |
        mkdir -p config/nginx/ssl
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout config/nginx/ssl/server.key \
          -out config/nginx/ssl/server.crt \
          -subj '/C=US/ST=Test/L=Test/O=Wazuh-CI/OU=Test/CN=localhost'
        ls -la config/nginx/ssl/
        
    - name: Start Wazuh stack with Docker Compose
      run: |
        cd wazuh-docker/single-node
        # Start services in background
        docker-compose up -d
        
        # Wait for services to start
        echo "Waiting for services to start..."
        sleep 60
        
        # Check service status
        docker-compose ps
        
    - name: Wait for services to be ready
      run: |
        cd wazuh-docker/single-node
        echo "Waiting for Wazuh services to be fully ready..."
        
        # Wait for Nginx health check (if nginx is configured in single-node)
        timeout 300 bash -c 'until curl -f http://localhost/health 2>/dev/null; do sleep 10; echo "Waiting for services..."; done' || echo "Direct health check not available"
        
        # Wait for Wazuh Dashboard
        timeout 300 bash -c 'until curl -f http://localhost:5601/app/login 2>/dev/null; do sleep 10; echo "Waiting for Wazuh Dashboard..."; done'
        
        # Wait for Wazuh API
        timeout 300 bash -c 'until curl -f http://localhost:55000/ 2>/dev/null; do sleep 10; echo "Waiting for Wazuh API..."; done'
        
        echo "All services are ready!"
        
    - name: Create test environment
      run: |
        cp tests/.env.example tests/.env
        cat >> tests/.env << EOF
        WAZUH_HOST=localhost
        WAZUH_PORT=5601
        WAZUH_DASHBOARD_PORT=5601
        WAZUH_API_PORT=55000
        WAZUH_USE_HTTPS=false
        HEADLESS=true
        CI=true
        WAZUH_TEST_USER=admin
        WAZUH_TEST_PASSWORD=SecretPassword
        EOF
        
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        
    - name: Run smoke tests
      run: |
        export CI=true
        export HEADLESS=true
        ./tests/run_tests.sh smoke
        
    - name: Run API tests
      run: |
        export CI=true
        ./tests/run_tests.sh api
        
    - name: Run UI tests
      run: |
        export CI=true
        export HEADLESS=true
        ./tests/run_tests.sh ui
        
    - name: Check HTTPS functionality
      run: |
        echo "Testing Wazuh endpoints..."
        
        # Test Wazuh Dashboard direct access
        echo "1. Testing Wazuh Dashboard direct access:"
        curl -I http://localhost:5601/ || true
        
        # Test Wazuh API direct access  
        echo "2. Testing Wazuh API direct access:"
        curl -I http://localhost:55000/ || true
        
        # Test Wazuh Indexer
        echo "3. Testing Wazuh Indexer:"
        curl -I -k https://localhost:9200/ || true
        
        # Show running containers
        echo "4. Running containers:"
        cd wazuh-docker/single-node
        docker-compose ps
        
    - name: Collect service logs on failure
      if: failure()
      run: |
        cd wazuh-docker/single-node
        echo "=== Docker Compose Status ==="
        docker-compose ps
        
        echo "=== Service Logs ==="
        echo "--- Wazuh Manager ---"
        docker-compose logs wazuh.manager
        
        echo "--- Wazuh Dashboard ---"  
        docker-compose logs wazuh.dashboard
        
        echo "--- Wazuh Indexer ---"
        docker-compose logs wazuh1.indexer
        
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: tests/reports/
        retention-days: 30
        
    - name: Cleanup
      if: always()
      run: |
        cd wazuh-docker/single-node
        docker-compose down -v
        docker system prune -f
