name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '35 15 * * 2' # Every Tuesday at 15:35 UTC

permissions:
  contents: read

jobs:
  trivy-indexer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull wazuh-indexer image
        run: docker pull wazuh/wazuh-indexer:4.12.0

      - name: Scan wazuh-indexer with Trivy
        uses:  aquasecurity/trivy-action@0.30.0
        with:
          image-ref: wazuh/wazuh-indexer:4.12.0
          format: 'sarif'
          output: 'trivy-results-wazuh-indexer.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-wazuh-indexer.sarif'

  trivy-manager:
    needs: trivy-indexer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull wazuh-manager image
        run: docker pull wazuh/wazuh-manager:4.12.0

      - name: Scan wazuh-manager with Trivy
        uses:  aquasecurity/trivy-action@0.30.0
        with:
          image-ref: wazuh/wazuh-manager:4.12.0
          format: 'sarif'
          output: 'trivy-results-wazuh-manager.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-wazuh-manager.sarif'

  trivy-dashboard:
    needs: trivy-manager
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull wazuh-dashboard image
        run: docker pull wazuh/wazuh-dashboard:4.12.0

      - name: Scan wazuh-dashboard with Trivy
        uses:  aquasecurity/trivy-action@0.30.0
        with:
          image-ref: wazuh/wazuh-dashboard:4.12.0
          format: 'sarif'
          output: 'trivy-results-wazuh-dashboard.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-wazuh-dashboard.sarif'

  selenium-tests:
    needs: trivy-dashboard
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Selenium tests
        run: |
          echo "Running Selenium tests..."
